# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0002_raidrecord_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raidrecord',
            old_name='screenshot',
            new_name='finish_screenshot',
        ),
        migrations.AddField(
            model_name='raidrecord',
            name='lineup_screenshot',
            field=models.ImageField(default=None, upload_to='raids'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raidrecord',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
