# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raids', '0003_auto_20180424_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidrecord',
            name='finish_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='raids'),
        ),
        migrations.AlterField(
            model_name='raidrecord',
            name='lineup_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='raids'),
        ),
        migrations.AlterField(
            model_name='raidrecord',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
