# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
