# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_auto_20170907_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='level',
        ),
    ]
