# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_remove_trainerbadge_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(upload_to='badge_applications')),
                ('note', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_applications', to='trainers.Badge')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_applications', to='trainers.Trainer')),
            ],
            options={
                'verbose_name_plural': 'Badge Applications',
                'verbose_name': 'Badge Application',
            },
        ),
    ]
