# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_badgeapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeapplication',
            name='screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to='badge_applications'),
        ),
    ]
