# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_badge_trainerbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerbadge',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
