# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_auto_20170907_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainerbadge',
            options={'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
    ]
