# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_badgeapplication_screenshot2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('xp', models.BigIntegerField()),
                ('pokemon_caught', models.IntegerField()),
                ('pokestops_spun', models.IntegerField()),
                ('battles_won', models.IntegerField()),
                ('kilometers_walked', models.FloatField()),
                ('pokedex_number', models.IntegerField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='trainers.Trainer')),
            ],
        ),
    ]
