# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_auto_20170907_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepokemon',
            name='number',
            field=models.IntegerField(choices=[(1, '1 - Bulbasaur2 - Ivysaur3 - Venusaur4 - Charmander5 - Charmeleon6 - Charizard7 - Squirtle8 - Wartortle9 - Blastoise10 - Caterpie11 - Metapod12 - Butterfree13 - Weedle14 - Kakuna15 - Beedrill16 - Pidgey17 - Pidgeotto18 - Pidgeot19 - Rattata20 - Raticate21 - Spearow22 - Fearow23 - Ekans24 - Arbok25 - Pikachu26 - Raichu27 - Sandshrew28 - Sandslash29 - Nidoran Female30 - Nidorina31 - Nidoqueen32 - Nidoran♂33 - Nidorino34 - Nidoking35 - Clefairy36 - Clefable37 - Vulpix38 - Ninetales39 - Jigglypuff40 - Wigglytuff41 - Zubat42 - Golbat43 - Oddish44 - Gloom45 - Vileplume46 - Paras47 - Parasect48 - Venonat49 - Venomoth50 - Diglett51 - Dugtrio52 - Meowth53 - Persian54 - Psyduck55 - Golduck56 - Mankey57 - Primeape58 - Growlithe59 - Arcanine60 - Poliwag61 - Poliwhirl62 - Poliwrath63 - Abra64 - Kadabra65 - Alakazam66 - Machop67 - Machoke68 - Machamp69 - Bellsprout70 - Weepinbell71 - Victreebel72 - Tentacool73 - Tentacruel74 - Geodude75 - Graveler76 - Golem77 - Ponyta78 - Rapidash79 - Slowpoke80 - Slowbro81 - Magnemite82 - Magneton83 - Farfetch’d84 - Doduo85 - Dodrio86 - Seel87 - Dewgong88 - Grimer89 - Muk90 - Shellder91 - Cloyster92 - Gastly93 - Haunter94 - Gengar95 - Onix96 - Drowzee97 - Hypno98 - Krabby99 - Kingler100 - Voltorb101 - Electrode102 - Exeggcute103 - Exeggutor104 - Cubone105 - Marowak106 - Hitmonlee107 - Hitmonchan108 - Lickitung109 - Koffing110 - Weezing111 - Rhyhorn112 - Rhydon113 - Chansey114 - Tangela115 - Kangaskhan116 - Horsea117 - Seadra118 - Goldeen119 - Seaking120 - Staryu121 - Starmie122 - Mr. Mime123 - Scyther124 - Jynx125 - Electabuzz126 - Magmar127 - Pinsir128 - Tauros129 - Magikarp130 - Gyarados131 - Lapras132 - Ditto133 - Eevee134 - Vaporeon135 - Jolteon136 - Flareon137 - Porygon138 - Omanyte139 - Omastar140 - Kabuto141 - Kabutops142 - Aerodactyl143 - Snorlax144 - Articuno145 - Zapdos146 - Moltres147 - Dratini148 - Dragonair149 - Dragonite150 - Mewtwo151 - Mew152 - Chikorita153 - Bayleef154 - Meganium155 - Cyndaquil156 - Quilava157 - Typhlosion158 - Totodile159 - Croconaw160 - Feraligatr161 - Sentret162 - Furret163 - Hoothoot164 - Noctowl165 - Ledyba166 - Ledian167 - Spinarak168 - Ariados169 - Crobat170 - Chinchou171 - Lanturn172 - Pichu173 - Cleffa174 - Igglybuff175 - Togepi176 - Togetic177 - Natu178 - Xatu179 - Mareep180 - Flaaffy181 - Ampharos182 - Bellossom183 - Marill184 - Azumarill185 - Sudowoodo186 - Politoed187 - Hoppip188 - Skiploom189 - Jumpluff190 - Aipom191 - Sunkern192 - Sunflora193 - Yanma194 - Wooper195 - Quagsire196 - Espeon197 - Umbreon198 - Murkrow199 - Slowking200 - Misdreavus201 - Unown202 - Wobbuffet203 - Girafarig204 - Pineco205 - Forretress206 - Dunsparce207 - Gligar208 - Steelix209 - Snubbull210 - Granbull211 - Qwilfish212 - Scizor213 - Shuckle214 - Heracross215 - Sneasel216 - Teddiursa217 - Ursaring218 - Slugma219 - Magcargo220 - Swinub221 - Piloswine222 - Corsola223 - Remoraid224 - Octillery225 - Delibird226 - Mantine227 - Skarmory228 - Houndour229 - Houndoom230 - Kingdra231 - Phanpy232 - Donphan233 - Porygon2234 - Stantler235 - Smeargle236 - Tyrogue237 - Hitmontop238 - Smoochum239 - Elekid240 - Magby241 - Miltank242 - Blissey243 - Raikou244 - Entei245 - Suicune246 - Larvitar247 - Pupitar248 - Tyranitar249 - Lugia250 - Ho-Oh')]),
        ),
    ]
