# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_auto_20171218_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='berries_fed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Berries Fed'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='eggs_hatched',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eggs Hatched'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='hours_defended',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hours Defended'),
        ),
        migrations.AddField(
            model_name='trainerupdate',
            name='berries_fed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Berries Fed'),
        ),
        migrations.AddField(
            model_name='trainerupdate',
            name='eggs_hatched',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eggs Hatched'),
        ),
        migrations.AddField(
            model_name='trainerupdate',
            name='hours_defended',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hours Defended'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='battles_won',
            field=models.IntegerField(verbose_name='Battles Won'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='kilometers_walked',
            field=models.FloatField(verbose_name='Kilometers Walked'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pokedex_number',
            field=models.IntegerField(verbose_name='Pokedex Entries'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pokemon_caught',
            field=models.IntegerField(verbose_name='Pokemon Caught'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='pokestops_spun',
            field=models.IntegerField(verbose_name='Pokestops Spun'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='Trainer Name'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='xp',
            field=models.BigIntegerField(verbose_name='Total XP'),
        ),
    ]
