# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_auto_20180413_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerupdate',
            name='berries_fed',
            field=models.IntegerField(default=0, verbose_name='Berries Fed'),
        ),
        migrations.AlterField(
            model_name='trainerupdate',
            name='eggs_hatched',
            field=models.IntegerField(default=0, verbose_name='Eggs Hatched'),
        ),
        migrations.AlterField(
            model_name='trainerupdate',
            name='hours_defended',
            field=models.IntegerField(default=0, verbose_name='Hours Defended'),
        ),
    ]
